### ISSUE TITLE
level loader that loads levels dynamically from a folder

### ISSUE THREAD

**Issue by TheMinesAreShakin** [jakemeinershagen/canyon-run#10]

**Comment by jakemeinershagen** [comment]
Okay, I'm going to try to start a list of things to get this working.

- [ ] move calls from `_enter_tree` in 'level.gd' to `start_level` in 'level_loader.gd
- [ ] move `@export var numOfLaps = 1` from 'level.gd' to a new script on the tilemap. the tilemap will be what we load as the track
- [ ] make the laptracker node a child of the tilemap
- [ ] change `start_level` in 'level_loader.gd' to have a parameter for the track
- [ ] create a track folder to store track scenes
- [ ] add loading of the track into `start_level` after the scene change (may need to check that the root node is loaded in first
- [ ] change the save and load in the level_loader to work for different tracks

12/06: I'll stare at this some tomorrow and try to decide if this looks like everything that needs done.

**Comment by jakemeinershagen** [comment]
>  will need some way of determining where to put the player ship on the track when loaded

I just created a lap template that has the start line in place. Should be an easy way to cheese it.
